export const themeImageMap = {
  default: await import('@/assets/images/themes/default.jpg'),
  classic: await import('@/assets/images/themes/classic.jpg'),
  minions: await import('@/assets/images/themes/minions.jpg'),
  pinkGrape: await import('@/assets/images/themes/pinkGrape.jpg'),
  mint: await import('@/assets/images/themes/mint.jpg'),
  gold: await import('@/assets/images/themes/gold.jpg'),
  vitalityOrange: await import('@/assets/images/themes/vitalityOrange.jpg'),
  greenLeaf: await import('@/assets/images/themes/greenLeaf.jpg'),
  dark2: await import('@/assets/images/themes/dark2.jpg'),
  skyGreen: await import('@/assets/images/themes/skyGreen.jpg'),
  classic2: await import('@/assets/images/themes/classic2.jpg'),
  classic3: await import('@/assets/images/themes/classic3.jpg'),
  classic4: await import('@/assets/images/themes/classic4.jpg'),
  classicGreen: await import('@/assets/images/themes/classicGreen.jpg'),
  classicBlue: await import('@/assets/images/themes/classicBlue.jpg'),
  blueSky: await import('@/assets/images/themes/blueSky.jpg'),
  brainImpairedPink: await import('@/assets/images/themes/brainImpairedPink.jpg'),
  dark: await import('@/assets/images/themes/dark.jpg'),
  earthYellow: await import('@/assets/images/themes/earthYellow.jpg'),
  freshGreen: await import('@/assets/images/themes/freshGreen.jpg'),
  freshRed: await import('@/assets/images/themes/freshRed.jpg'),
  romanticPurple: await import('@/assets/images/themes/romanticPurple.jpg'),
  simpleBlack: await import('@/assets/images/themes/simpleBlack.jpg'),
  courseGreen: await import('@/assets/images/themes/courseGreen.jpg'),
  coffee: await import('@/assets/images/themes/coffee.jpg'),
  redSpirit: await import('@/assets/images/themes/redSpirit.jpg'),
  blackHumour: await import('@/assets/images/themes/blackHumour.jpg'),
  lateNightOffice: await import('@/assets/images/themes/lateNightOffice.jpg'),
  blackGold: await import('@/assets/images/themes/blackGold.jpg'),
  autumn: await import('@/assets/images/themes/autumn.jpg'),
  avocado: await import('@/assets/images/themes/avocado.jpg'),
  orangeJuice: await import('@/assets/images/themes/orangeJuice.jpg'),
  oreo: await import('@/assets/images/themes/oreo.jpg'),
  shallowSea: await import('@/assets/images/themes/shallowSea.jpg'),
  lemonBubbles: await import('@/assets/images/themes/lemonBubbles.jpg'),
  rose: await import('@/assets/images/themes/rose.jpg'),
  seaBlueLine: await import('@/assets/images/themes/seaBlueLine.jpg'),
  neonLamp: await import('@/assets/images/themes/neonLamp.jpg'),
  darkNightLceBlade: await import('@/assets/images/themes/darkNightLceBlade.jpg'),
  morandi: await import('@/assets/images/themes/morandi.jpg'),
  classic5: await import('@/assets/images/themes/classic5.jpg'),
  dark3: await import('@/assets/images/themes/dark3.jpg'),
  dark4: await import('@/assets/images/themes/dark4.jpg'),
  cactus: await import('@/assets/images/themes/cactus.jpg'),
  classic6: await import('@/assets/images/themes/classic6.jpg'),
  classic7: await import('@/assets/images/themes/classic7.jpg'),
};

export const baiduThemes = [
  "default",
  "skyGreen",
  "classic2",
  "classic3",
  "classicGreen",
  "classicBlue",
  "blueSky",
  "brainImpairedPink",
  "earthYellow",
  "freshGreen",
  "freshRed",
  "romanticPurple",
  "pinkGrape",
  "mint",
];
